In [4]:
"""
https://zhuanlan.zhihu.com/p/24309547
"""
import numpy as np

## 1. 创建 array对象

In [25]:
a = np.array([[1, 2, 3, 4], [2, 1, 2, 5]])
np.zeros((2, 3))
np.ones((2, 3))
np.zeros_like(a)
np.ones_like(a)

array([[1, 1, 1, 1],
       [1, 1, 1, 1]])

In [26]:
np.arange(1, 100, 5)

array([ 1,  6, 11, 16, 21, 26, 31, 36, 41, 46, 51, 56, 61, 66, 71, 76, 81,
       86, 91, 96])

In [65]:
np.linspace(0, 6, 10)

array([ 0.        ,  0.66666667,  1.33333333,  2.        ,  2.66666667,
        3.33333333,  4.        ,  4.66666667,  5.33333333,  6.        ])

In [59]:
np.ones((3,3), dtype=np.float)

array([[ 1.,  1.,  1.],
       [ 1.,  1.,  1.],
       [ 1.,  1.,  1.]])

In [66]:
re = np.repeat(2, 4)
re

array([2, 2, 2, 2])

In [67]:
re.astype(np.float)

array([ 2.,  2.,  2.,  2.])

## 2. 属性

In [33]:
print(a.shape) #tuple
print(a.size)

(2, 4)
8


## 3. 方法

In [38]:
a

array([[1, 2, 3, 4],
       [2, 1, 2, 5]])

In [34]:
# 按行来比较, 得到每一列中, 最大值所在行的 index
a.argmax() # 7
a.argmax(axis=0)

array([1, 0, 0, 1])

In [40]:
# 按行来比较, 得到每一列中, 最大值
a.max()
a.max(axis=0)

array([2, 2, 3, 5])

In [45]:
a.mean() # 2.5
a.mean(axis=0)

array([ 1.5,  1.5,  2.5,  4.5])

## 4. 变换

In [48]:
a.flatten()

array([1, 2, 3, 4, 2, 1, 2, 5])

In [53]:
np.ravel(a)

array([1, 2, 3, 4, 2, 1, 2, 5])

In [55]:
# 两者所要实现的功能是一致的（将多维数组降位一维），
# 两者的区别在于返回拷贝（copy）还是返回视图（view），
# numpy.flatten()返回一份拷贝，对拷贝所做的修改不会影响（reflects）原始矩阵，
# 而numpy.ravel()返回的是视图（view，也颇有几分C/C++引用reference的意味），会影响（reflects）原始矩阵。
a.flatten()[1] = 100
print(a)

np.ravel(a)[1] = 100
print(a)

[[1 2 3 4]
 [2 1 2 5]]
[[  1 100   3   4]
 [  2   1   2   5]]


In [57]:
c = np.array([[1],[2],[3]])
c

array([[1],
       [2],
       [3]])

In [58]:
c.squeeze()

array([1, 2, 3])

In [78]:
a.reshape((4, 2))
np.reshape(a, -1)

array([  1, 100,   3,   4,   2,   1,   2,   5])

In [79]:
a.reshape((4, -1))

array([[  1, 100],
       [  3,   4],
       [  2,   1],
       [  2,   5]])

## 5. 组合

In [82]:
l0 = np.arange(6).reshape((2, 3))
l1 = np.arange(6, 12).reshape((2, 3))
l0

array([[0, 1, 2],
       [3, 4, 5]])

In [83]:
l1

array([[ 6,  7,  8],
       [ 9, 10, 11]])

In [85]:
stack1 = np.stack((l0, l1))
print(stack1.shape)
stack1

(2, 2, 3)


array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]])

In [86]:
stackv = np.vstack((l0, l1))
print(stackv.shape)
stackv

(4, 3)


array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [87]:
stackh = np.hstack((l0, l1))
print(stackh.shape)
stackh

(2, 6)


array([[ 0,  1,  2,  6,  7,  8],
       [ 3,  4,  5,  9, 10, 11]])

## 6. 运算

In [ ]:
np.abs(-1)
np.sin(np.pi/2)
np.arctanh(0.462118) # tanh逆函数，0.50000107157840523
np.exp(3)
np.power(2, 3) # **
np.dot([1, 2], [3, 4])
np.sqrt(25)
np.sum([1, 2, 3, 4])
np.mean([4, 5, 6, 7])
np.std([1, 2, 3, 2, 1, 3, 2, 0])

## 7. 随机模块

In [40]:
import numpy as np
import numpy.random as random

In [41]:
# 产生一个1x3，[0,1)之间的浮点型随机数
random.rand(1, 3)

array([[ 0.98922498,  0.64177842,  0.9235004 ]])

In [42]:
# 产生一个[0,1)之间的浮点型随机数
random.random()

0.9203287412560559

In [43]:
# 下边4个没有区别，都是按照指定大小产生[0,1)之间的浮点型随机数array，不Pythonic…
random.random((3, 3))
random.sample((3, 3))
random.random_sample((3, 3))
random.ranf((3, 3))

array([[ 0.23425077,  0.53868022,  0.24606067],
       [ 0.28708382,  0.5750244 ,  0.06586393],
       [ 0.7756696 ,  0.15461368,  0.64046766]])

In [47]:
# 产生10个[1,6)之间的浮点型随机数 均匀分布
5*random.random(10) + 1
random.uniform(1, 6, 10)

array([ 5.084373  ,  3.04820209,  2.49333836,  5.45494239,  2.4229939 ,
        3.71701585,  5.04037538,  2.09551003,  3.69454799,  3.54241783])

In [45]:
# 产生10个[1,6)之间的整型随机数
random.randint(1, 6, 10)

array([4, 4, 2, 2, 2, 5, 1, 1, 2, 4])

In [46]:
# 产生2x5的标准正态分布样本
random.normal(size=(5, 2))

array([[-1.55450591,  1.04626225],
       [-0.79307154,  2.04320485],
       [ 0.24569102, -1.3275046 ],
       [ 0.19236119,  0.9508846 ],
       [-0.09374494,  0.78502365]])

In [62]:
# 生成一个长度为9的随机bytes序列并作为str返回
# '\x96\x9d\xd1?\xe6\x18\xbb\x9a\xec'
random.bytes(9)

b'N\xa2\xe5QS\xf99\xfa\x18'

### 7.1 随机采样 & 打乱

In [49]:
a = np.arange(10)

# 从a中有回放的随机采样7个
random.choice(a, 7)

array([6, 2, 0, 5, 6, 2, 1])

In [54]:
# 从a中无回放的随机采样7个
random.choice(a, 7, replace=False)

array([6, 2, 9, 0, 4, 8, 7])

In [58]:
# 对a进行乱序并返回一个新的array
print(a)
random.permutation(a)

[0 1 2 3 4 5 6 7 8 9]


array([9, 4, 0, 3, 7, 1, 6, 2, 8, 5])

In [61]:
# 对a进行in-place乱序
random.shuffle(a)
a

array([6, 4, 9, 5, 1, 0, 3, 7, 8, 2])