In [7]:
"""
https://zhuanlan.zhihu.com/p/24309547
"""
import numpy as np

## 1. 创建 array对象

In [8]:
a = np.array([[1, 2, 3, 4], [2, 1, 2, 5]])
np.zeros((2, 3))
np.ones((2, 3))
np.zeros_like(a)
np.ones_like(a)

array([[1, 1, 1, 1],
       [1, 1, 1, 1]])

In [9]:
np.arange(1, 100, 5)

array([ 1,  6, 11, 16, 21, 26, 31, 36, 41, 46, 51, 56, 61, 66, 71, 76, 81,
       86, 91, 96])

In [10]:
np.linspace(0, 6, 10)

array([ 0.        ,  0.66666667,  1.33333333,  2.        ,  2.66666667,
        3.33333333,  4.        ,  4.66666667,  5.33333333,  6.        ])

In [11]:
np.ones((3,3), dtype=np.float)

array([[ 1.,  1.,  1.],
       [ 1.,  1.,  1.],
       [ 1.,  1.,  1.]])

In [12]:
re = np.repeat(2, 4)
re

array([2, 2, 2, 2])

In [13]:
re.astype(np.float)

array([ 2.,  2.,  2.,  2.])

## 2. 属性

In [14]:
print(a.shape) #tuple
print(a.size)

(2, 4)
8


## 3. 方法

In [15]:
a

array([[1, 2, 3, 4],
       [2, 1, 2, 5]])

In [16]:
# 按行来比较, 得到每一列中, 最大值所在行的 index
a.argmax() # 7
a.argmax(axis=0)

array([1, 0, 0, 1])

In [17]:
# 按行来比较, 得到每一列中, 最大值
a.max()
a.max(axis=0)

array([2, 2, 3, 5])

In [18]:
a.mean() # 2.5
a.mean(axis=0)

array([ 1.5,  1.5,  2.5,  4.5])

## 4. 变换

In [19]:
a.flatten()

array([1, 2, 3, 4, 2, 1, 2, 5])

In [20]:
np.ravel(a)

array([1, 2, 3, 4, 2, 1, 2, 5])

In [21]:
# 两者所要实现的功能是一致的（将多维数组降位一维），
# 两者的区别在于返回拷贝（copy）还是返回视图（view），
# numpy.flatten()返回一份拷贝，对拷贝所做的修改不会影响（reflects）原始矩阵，
# 而numpy.ravel()返回的是视图（view，也颇有几分C/C++引用reference的意味），会影响（reflects）原始矩阵。
a.flatten()[1] = 100
print(a)

np.ravel(a)[1] = 100
print(a)

[[1 2 3 4]
 [2 1 2 5]]
[[  1 100   3   4]
 [  2   1   2   5]]


In [22]:
c = np.array([[1],[2],[3]])
c

array([[1],
       [2],
       [3]])

In [23]:
c.squeeze()

array([1, 2, 3])

In [24]:
a.reshape((4, 2))
np.reshape(a, -1)

array([  1, 100,   3,   4,   2,   1,   2,   5])

In [25]:
a.reshape((4, -1))

array([[  1, 100],
       [  3,   4],
       [  2,   1],
       [  2,   5]])

## 5. 组合

In [26]:
l0 = np.arange(6).reshape((2, 3))
l1 = np.arange(6, 12).reshape((2, 3))
l0

array([[0, 1, 2],
       [3, 4, 5]])

In [27]:
l1

array([[ 6,  7,  8],
       [ 9, 10, 11]])

In [28]:
stack1 = np.stack((l0, l1))
print(stack1.shape)
stack1

(2, 2, 3)


array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]])

In [29]:
stackv = np.vstack((l0, l1))
print(stackv.shape)
stackv

(4, 3)


array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [30]:
stackh = np.hstack((l0, l1))
print(stackh.shape)
stackh

(2, 6)


array([[ 0,  1,  2,  6,  7,  8],
       [ 3,  4,  5,  9, 10, 11]])

## 6. 运算

In [31]:
np.abs(-1)
np.sin(np.pi/2)
np.arctanh(0.462118) # tanh逆函数，0.50000107157840523
np.exp(3)
np.power(2, 3) # **
np.dot([1, 2], [3, 4])
np.sqrt(25)
np.sum([1, 2, 3, 4])
np.mean([4, 5, 6, 7])
np.std([1, 2, 3, 2, 1, 3, 2, 0])

0.96824583655185426

In [32]:
tf = np.array([True, True, False, True, False])
print(tf)
tf*np.ones(5)

[ True  True False  True False]


array([ 1.,  1.,  0.,  1.,  0.])

## 7. 随机模块

In [33]:
import numpy as np
import numpy.random as random

In [34]:
# 产生一个1x3，[0,1)之间的浮点型随机数
random.rand(1, 3)

array([[ 0.58397107,  0.94786968,  0.83549033]])

In [35]:
# 产生一个[0,1)之间的浮点型随机数
random.random()

0.9344501411058088

In [36]:
# 下边4个没有区别，都是按照指定大小产生[0,1)之间的浮点型随机数array，不Pythonic…
random.random((3, 3))
random.sample((3, 3))
random.random_sample((3, 3))
random.ranf((3, 3))

array([[ 0.1192258 ,  0.70035888,  0.87019164],
       [ 0.14007322,  0.23177812,  0.17252596],
       [ 0.88778737,  0.20170321,  0.21825884]])

In [37]:
# 产生10个[1,6)之间的浮点型随机数 均匀分布
5*random.random(10) + 1
random.uniform(1, 6, 10)

array([ 2.47583946,  5.31035548,  2.61179265,  1.1157438 ,  5.57596726,
        5.86478429,  1.38430893,  5.30324073,  3.88513661,  5.31050521])

In [38]:
# 产生10个[1,6)之间的整型随机数
random.randint(1, 6, 10)

array([2, 2, 4, 3, 2, 5, 1, 4, 2, 3])

In [39]:
# 产生2x5的标准正态分布样本
random.normal(size=(5, 2))

array([[ 0.07557013,  1.88216226],
       [-0.40423297, -0.55121454],
       [ 0.39258489,  0.07024418],
       [ 2.18938725,  2.69190607],
       [ 0.83400525, -0.69394247]])

In [40]:
# 生成一个长度为9的随机bytes序列并作为str返回
# '\x96\x9d\xd1?\xe6\x18\xbb\x9a\xec'
random.bytes(9)

b'fV|\x9f\x80\xf9U5\xac'

### 7.1 随机采样 & 打乱

In [41]:
a = np.arange(10)

# 从a中有回放的随机采样7个
random.choice(a, 7)

array([8, 1, 7, 3, 5, 7, 6])

In [42]:
# 从a中无回放的随机采样7个
random.choice(a, 7, replace=False)

array([9, 7, 0, 1, 2, 3, 5])

In [43]:
# 对a进行乱序并返回一个新的array
print(a)
random.permutation(a)

[0 1 2 3 4 5 6 7 8 9]


array([1, 6, 2, 9, 8, 7, 4, 5, 3, 0])

In [44]:
# 对a进行in-place乱序
random.shuffle(a)
a

array([7, 6, 4, 5, 0, 8, 1, 9, 3, 2])

## 8. 排序

In [47]:
a[a.argsort()] 

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [48]:
a[a.argsort()[::-1]]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])